interface AddDeliverySiteARequest {
    "connectid": string,
    "customerid": string,
    "SiteCode": string,
    "Name": string,
    "Address1": string,
    "Address2": string,
    "City": string,
    "State": string,
    "PostalCode": string,
    "Country": string,
    "Contact": string,
    "Phone": string,
    "Fax": string,
    "Email": string,
    "FreightType": string,
    "FreightAccount": string,
    "Carrier": string,
    "Shipping": string,
    "Primary": boolean,
    "Mobile": string,
    "InternalUse1": string,
    "InternalUse2": string,
}
//The SiteCode, Name, Address1, City, State, PostalCode, Contact, Phone and Email are mandatory.