interface GetCustomerBReturn {
    "success": true, // if the customers details were retrieved successfully
    "payload": {
        "Name": string,
        "Abbreviation": string,
        "Address1": string,
        "Address2": string,
        "City": string,
        "State": string,
        "PostalCode": string,
        "Country": string,
        "Phone": string,
        "Fax": string,
        "Email": string,
        "AccountType": string,
        "Currency": string,
        "SalesLocation": string,
        "BusinessNumber": string,
        "AccountNumber": string,
        "MailOut": string,
        "EnforeOrder": boolean,
        "SalesCategory": string,
        "SalesID": string,
        "SendOrderAck": string,
        "consignmentWarehouse": string,
        "InternalUse2": string,
        "InternalUse3": string,
        "UserDefinedField1": string,
        "UserDefinedField2": string,
        "UserDefinedField3": string,
        "UserDefinedField4": string,
        "UserDefinedField5": string,
        "UserDefinedField6": string,
    }
}
