interface AddContactRequest {
    "connectid" : string,
    "contact" : {
        "ContactID" : string,
        "ContactType" : string,
        "ContactTypeDescription" : string,
        "Contact" : string,
        "ContactTitle" : string,
        "Salute" : string,
        "FirstName" : string,
        "LastName" : string,
        "Address1" : string,
        "Address2" : string,
        "City" : string,
        "State" : string,
        "PostalCode" : string,
        "Country" : string,
        "Phone" : string,
        "Mobile" : string,
        "Fax" : string,
        "Email" : string,
        "PrimaryContact" : boolean,
    },
}
//The ContactID and ContactType are mandatory.
