interface AddContactARequest {
    "connectid": string,
    "customerid": string,
    "ContactType": string,
    "Contact": string,
    "Title": string,
    "Salute": string,
    "FirstName": string,
    "LastName": string,
    "Address1": string,
    "Address2": string,
    "City": string,
    "State": string,
    "PostalCode": string,
    "Country": string,
    "Phone": string,
    "Mobile": string,
    "Fax": string,
    "Email": string,
    "Primary": boolean,
    "InternalUse1": string,
    "InternalUse2": string,
    "InternalUse3": string,
}
//Contact and ContactType are mandatory.