interface GetCustomerAReturn { //CustomerDetail type containing customer information.
    "CustomerID": string,
    "Name": string,
    "Abbreviation": string,
    "Address1": string,
    "Address2": string,
    "City": string,
    "State": string,
    "PostalCode": string,
    "Country": string,
    "Phone": string,
    "Fax": string,
    "Email": string,
    "AccountType": string,
    "Currency": string,
    "SalesLocation": string,
    "BusinessNumber": string,
    "AccountNumber": string,
    "MailOut": string,
    "Mobile": string,
    "SalesID": string,
    "UserDefinedField1": string,
    "UserDefinedField2": string,
    "UserDefinedField3": string,
    "UserDefinedField4": string,
    "UserDefinedField5": string,
    "UserDefinedField6": string,
}
